# autogenerated by txs
#include:amsfonts
#include:amsmath
#include:amssymb
#include:ifthen
#include:kvoptions
#include:xcolor
#include:mathworkMathTUD
\begin{exercisePage}#S
\end{exercisePage}#S
\header#S

\begin{doodlebox}[framecolor][backgroundcolor]
\end{doodlebox}
\begin{doodle}{color}
\end{doodle}
\scorebox{score}
\task{arg}
\subtask{arg}
